# Generated by Django 5.0.6 on 2024-07-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField(default=0)),
                ('is_vip', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ticket_number', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.passenger')),
            ],
        ),
    ]
