# Generated by Django 5.0.6 on 2024-08-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger', '0001_initial'),
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('icao_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('registration', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='images/aircraft/')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('icao_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('iso_country', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('flight_time', models.CharField(max_length=6)),
                ('phase', models.IntegerField(choices=[(0, 'Preflight'), (1, 'Boarding'), (2, 'Departing'), (3, 'Cruising'), (4, 'Landed'), (5, 'Arrived')], default=0)),
                ('callsign', models.CharField(max_length=8)),
                ('departure_time', models.DateTimeField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flight.aircraft')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flight.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flight.airport')),
                ('passengers', models.ManyToManyField(blank=True, to='passenger.passenger')),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pilot.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='StandardRoute',
            fields=[
                ('flight_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flight.aircraft')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flight.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flight.airport')),
            ],
        ),
    ]
