# Generated by Django 5.0.6 on 2024-09-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
