# Generated by Django 5.0.6 on 2024-07-24 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
        ('passenger', '0001_initial'),
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('flt_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('callsign', models.CharField(max_length=8)),
                ('acf_type', models.CharField(max_length=8)),
                ('departure_time', models.DateTimeField()),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flight.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='flight.airport')),
                ('passengers', models.ManyToManyField(blank=True, to='passenger.passenger')),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pilot.pilot')),
            ],
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
