# Generated by Django 5.0.6 on 2024-08-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightschedule',
            name='callsign',
        ),
    ]
