# Generated by Django 5.0.6 on 2024-08-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/aircraft/'),
        ),
    ]
