# Generated by Django 5.0.6 on 2024-08-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_aircraft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='phase',
            field=models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Boarding'), (2, 'Departing'), (3, 'Cruising'), (4, 'Landed'), (5, 'Arrived')], default=0),
        ),
    ]
