/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AirportModal: typeof import('./src/components/modal/AirportModal.vue')['default']
    AuthLayout: typeof import('./src/components/layout/AuthLayout.vue')['default']
    BasicMenu: typeof import('./src/components/menu/BasicMenu.vue')['default']
    Checkbox: typeof import('./src/components/input/Checkbox.vue')['default']
    Dispatcher: typeof import('./src/components/widget/Dispatcher.vue')['default']
    Gravatar: typeof import('./src/components/icon/Gravatar.vue')['default']
    IconBanner: typeof import('./src/components/icon/IconBanner.vue')['default']
    IconLogo: typeof import('./src/components/icon/IconLogo.vue')['default']
    InputMessage: typeof import('./src/components/input/InputMessage.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    Modal: typeof import('./src/components/modal/Modal.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NeoButton: typeof import('./src/components/input/NeoButton.vue')['default']
    Notam: typeof import('./src/components/widget/Notam.vue')['default']
    OpsLayout: typeof import('./src/components/layout/OpsLayout.vue')['default']
    PilotMenu: typeof import('./src/components/menu/PilotMenu.vue')['default']
    Roster: typeof import('./src/components/widget/Roster.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitFlipDisplay: typeof import('./src/components/SplitFlipDisplay.vue')['default']
    SplitFlipDisplayChar: typeof import('./src/components/SplitFlipDisplayChar.vue')['default']
    Stats: typeof import('./src/components/widget/Stats.vue')['default']
    TextArea: typeof import('./src/components/input/TextArea.vue')['default']
    TextInput: typeof import('./src/components/input/TextInput.vue')['default']
  }
}
