# Generated by Django 5.0.6 on 2024-09-08 03:42

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('handle', models.CharField(max_length=32, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('display_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('bio', models.TextField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('receive_emails', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[(1, 'Register'), (2, 'Change Email'), (3, 'Reset Password')], max_length=32)),
                ('token', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=64)),
                ('valid_until', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
