# Generated by Django 5.0.6 on 2024-07-17 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='member',
            name='receive_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AuthRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[(1, 'Register'), (2, 'Change Email'), (3, 'Reset Password')], max_length=32)),
                ('token', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=64)),
                ('valid_until', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterEmailToken',
        ),
    ]
