# Generated by Django 5.0.6 on 2024-07-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_receive_emails_authrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='reason',
            field=models.CharField(choices=[(1, 'Register'), (2, 'Change Email'), (3, 'Reset Password')], max_length=32),
        ),
    ]
